name: CI
on: [ push, pull_request ]
jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        integration-deps:
        - ""
        - "diagram-js@^14"

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Use Node.js 20
      uses: actions/setup-node@v5
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install dependencies for integration test
      if: ${{ matrix.integration-deps != '' }}
      run: npm install ${{ matrix.integration-deps }}
    - name: Setup project
      uses: bpmn-io/actions/setup@latest
    - name: Build
      env:
        TEST_BROWSERS: ChromeHeadless
      run: npm run all
